### ISSUE TITLE
Memory leak when updating map.

### ISSUE THREAD

**Issue by Aberro** [KSPModStewards/SCANsat#382] opened 2020-06-28 20:36 UTC
As title says - each time map is updated (especially zoomed in window with autoupdate enabled), KSP allocates few hundreds megabytes and never releases it. It's just keeps growing until OutOfMemoryException.

**Comment by DMagic1** [comment] 2020-06-29 19:51
I see it. The problem is related to the textures for the visible scan maps being regenerated when they shouldn't be, then not getting destroyed properly.

This will be fixed in the next update, hopefully sometime this week.

**Comment by Aberro** [comment] 2020-06-29 23:01
Nice. I'll be waiting for it.

**Comment by DMagic1** [comment] 2020-07-08 02:42
The leak should be fixed in version 20.2, and memory usage in general is reduced for the visual maps.

**Closed as completed by DMagic1** 2020-07-08 02:42 UTC

**Comment by Aberro** [comment] 2020-07-08 07:58
Thank you!)
