### ISSUE TITLE
Enhancement Request: Image Mapping

### ISSUE THREAD

**Issue by pap1723** [KSPModStewards/SCANsat#226] opened 2016-07-15 16:09 UTC
Hi DMagic!

I absolutely love SCANsat and DMagic Orbital Science and I don't think I have played a game without both since my first days of KSP!

I have a feature request for SCANsat and I don't know if it is possible. The very first satellites that were used to map planets such as Luna 10 (the Moon) basically used images only as their mapping devices. Right now, Altimetry sensors come very early on the tech tree and adding a photographic satellite function would be awesome and a good starting point.

I am assuming that the scans access the Height Maps and Biome Maps provided for the planets. The scan I am referencing could access the Texture map.

There could also be a High Resolution Imagery one that comes much later in the tech tree that would simulate what we see with Google and Bing maps, etc.

Well, that is all I have and thanks for reading this.

Pap

**Comment by DMagic1** [comment] 2016-07-19 23:59
This is a duplicate of #10, so I'll close this.

But there are a few problems that make this unlikely to be added.

One is that it seems funny to have a perfect visual image of the planet available from the map view or the tracking station, but to have to scan it to get the same image onto a SCANsat map.

Related to that, actually obfuscating the planet's texture isn't really feasible when trying to apply SCANsat-type scanning. It's possible to make the entire planet's texture less detailed, but trying to make certain areas highly detailed and other with lower detailed presents all kinds of problems. And I don't want to add a visual scanning system that differs significantly from the existing SCANsat methods.

SCANsat doesn't actually look at the height map or biome map for a planet. The hieght map is just the starting point for generating terrain, and it doesn't actually match the final terrain for a planet. It also isn't detailed enough to make good maps; the same goes for the biome maps. SCANsat accesses the final terrain and biome data for a given location.

The visual texture maps also don't always match the final result, Kerbin is just a black and white image.

The Google Maps version of a map also probably wouldn't work. The textures aren't that highly detailed, and generating the visual data on-the-fly probably isn't feasible.

**Closed as completed by DMagic1** 2016-07-19 23:59 UTC
