### ISSUE TITLE
Active BTDT near the Anomaly breaks Instrumets window

### ISSUE THREAD

**Issue by WildLynxDev** [KSPModStewards/SCANsat#266] opened 2017-04-08 17:58 UTC
BTDT and anomaly problem again.
This time on Moho.

I was landing on Moho near the anomaly.

BTDT on, instruments window visible.

But, when I got to anomaly close enough for instrument window to show 3D map, it went blank instead.

Turning off BTDT restores instrument window, turning BTDT on makes it blank.

Also, Exception detector reports exceptions: 
Unity.Engine.Material..ctor.

Note 2 dots. 

http://imgur.com/5lx7EdY.png
http://imgur.com/7DmxJqJ.png

Logs:

https://www.dropbox.com/s/4mmzvbuk0vsiiin/08APR2017.tar.gz?dl=0

KSP 1.2.2, SCANSAT 1.1.6.11, Linux Mageia 5 x64

**Comment by DMagic1** [comment] 2017-04-08 18:22
It's a problem with the shaders in Unity 5.4.

The issue is fixed in the latest dev version:
https://github.com/S-C-A-N/SCANsat/releases/tag/v17.5

A full release should happen sometime after KSP 1.3 is out.

**Comment by DMagic1** [comment] 2017-07-10 14:23
Fixed in version 18.

**Closed as completed by DMagic1** 2017-07-10 14:23 UTC
