### ISSUE TITLE
Scansat altimetry map not closing

### ISSUE THREAD

**Issue by mpredosin** [KSPModStewards/SCANsat#261] opened 2017-03-08 02:32 UTC
The map window is not closing when clicking the X at the top right corner.   I'm able to create additional map windows.  The maps are still displayed after exiting out to the main menu.  Restarting the game is the only way to get rid of them.

**Comment by DMagic1** [comment] 2017-03-08 02:41
Which window has the problem, all of them? 

Does clicking any of the other buttons to close the window do anything?

Which version is this?

Do you have log files?

**Comment by mpredosin** [comment] 2017-03-08 02:52
Which window has the problem, all of them?
Only the big altimetry map window

Does clicking any of the other buttons to close the window do anything?
No

Which version is this?
1.1.7.2

Do you have log files?
How do I get a log file for scansat?

**Comment by DMagic1** [comment] 2017-03-08 02:56
Try the newest version 17.4. Delete the old installation first.

http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

This has instructions for log files.

**Comment by mpredosin** [comment] 2017-03-08 03:02
That fixed it.  Thanks!

**Comment by mpredosin** [comment] 2017-03-08 18:04
I was able to reproduce the issue on 17.4.

Here's a screenshot.
![20170308100303_1](https://cloud.githubusercontent.com/assets/253549/23716874/950aa542-03e6-11e7-9fa4-abcbdbf5df44.jpg)

The windows persist when exiting to the main menu:
![20170308100541_1](https://cloud.githubusercontent.com/assets/253549/23716963/e1b4632e-03e6-11e7-809e-9a1a85a62aa4.jpg)

**Comment by DMagic1** [comment] 2017-03-08 18:50
I still need log files.

**Comment by 81ninja** [comment] 2017-06-11 19:47
I'm having this problem with the big map on KSP 1.3 / SCANSat latest dev branch (as of today).

It'll happens sometimes randomly during gameplay, but I found it can be reproduced quite easily by spamming the big map show/hide button on the SCANSat app launcher in the stock toolbar while in flight (controlling a vessel). If you click the button again before the window has completely faded in/out, a new window opens and can't be closed anymore.

![screenshot177](https://user-images.githubusercontent.com/22650639/27013989-30e6f0aa-4ec5-11e7-8bd3-a5ab770321ee.png)

[KSP.log.txt](https://github.com/S-C-A-N/SCANsat/files/1066712/KSP.log.txt)

**Comment by DMagic1** [comment] 2017-06-11 20:43
I see the problem now.

It's just a silly error when opening the window from the toolbar button. The state of the button is not getting set, so it thinks you want to open it every time you click on it. The button's state is reset if you close the toolbar menu and re-open it, but it will still have the problem if you do a close-open-close again.

**Comment by 81ninja** [comment] 2017-06-11 22:28
Ok so the fix is a 1-liner :) I've added a check and the issue is gone.

**Comment by DMagic1** [comment] 2017-07-10 14:24
Fixed in version 18.

**Closed as completed by DMagic1** 2017-07-10 14:24 UTC
