### ISSUE TITLE
BoxColliders with negative scaling

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSPModStewards/SCANsat#390] opened 2020-09-11 23:58 UTC
```
[LOG 16:27:12.230] Load(Model): SCANsat/Parts/scansat-radar/scansat-radar-seasat-1
[WRN 16:27:12.240] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "SeaSat/ScanSat_SAR_Seasat/B_SeaSatArmBase/B_SeaSatArm/B_SeaSatArmRoot/B_SeaSat_PanelMainNode/B_SeaSat_PanelRotationNode/B_SeaSat_PanelAB_Node/B_SeaSat_PanelA_Root/B_SeaSat_PanelA_R_001/SeaSatPanel002"
[WRN 16:27:12.240] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "SeaSat/ScanSat_SAR_Seasat/B_SeaSatArmBase/B_SeaSatArm/B_SeaSatArmRoot/B_SeaSat_PanelMainNode/B_SeaSat_PanelRotationNode/B_SeaSat_PanelAB_Node/B_SeaSat_PanelB_Root/B_SeaSat_PanelA_R_002/SeaSatPanel004"
[WRN 16:27:12.241] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "SeaSat/ScanSat_SAR_Seasat/B_SeaSatArmBase/B_SeaSatArm/B_SeaSatArmRoot/B_SeaSat_PanelMainNode/B_SeaSat_PanelRotationNode/B_SeaSat_PanelAB_Node001/B_SeaSat_PanelA_Root001/B_SeaSat_PanelA_R_003/SeaSatPanel006"
[WRN 16:27:12.241] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "SeaSat/ScanSat_SAR_Seasat/B_SeaSatArmBase/B_SeaSatArm/B_SeaSatArmRoot/B_SeaSat_PanelMainNode/B_SeaSat_PanelRotationNode/B_SeaSat_PanelAB_Node001/B_SeaSat_PanelB_Root001/B_SeaSat_PanelA_R_004/SeaSatPanel008"
```
Affected parts:

- SeaSat/ScanSat_SAR_Seasat/B_SeaSatArmBase/B_SeaSatArm/B_SeaSatArmRoot/B_SeaSat_PanelMainNode/B_SeaSat_PanelRotationNode/B_SeaSat_PanelAB_Node/B_SeaSat_PanelA_Root/B_SeaSat_PanelA_R_001/SeaSatPanel002
- SeaSat/ScanSat_SAR_Seasat/B_SeaSatArmBase/B_SeaSatArm/B_SeaSatArmRoot/B_SeaSat_PanelMainNode/B_SeaSat_PanelRotationNode/B_SeaSat_PanelAB_Node/B_SeaSat_PanelA_Root/B_SeaSat_PanelA_R_001/SeaSatPanel004
- SeaSat/ScanSat_SAR_Seasat/B_SeaSatArmBase/B_SeaSatArm/B_SeaSatArmRoot/B_SeaSat_PanelMainNode/B_SeaSat_PanelRotationNode/B_SeaSat_PanelAB_Node/B_SeaSat_PanelA_Root/B_SeaSat_PanelA_R_001/SeaSatPanel006
- SeaSat/ScanSat_SAR_Seasat/B_SeaSatArmBase/B_SeaSatArm/B_SeaSatArmRoot/B_SeaSat_PanelMainNode/B_SeaSat_PanelRotationNode/B_SeaSat_PanelAB_Node/B_SeaSat_PanelA_Root/B_SeaSat_PanelA_R_001/SeaSatPanel008

**Comment by DMagic1** [comment] 2020-09-12 01:12
Duplicate of #365.

**Closed as completed by DMagic1** 2020-09-12 01:12 UTC
